name: Nuget Package Deploy

on: 
 push:
   branches: 
     - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2     
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore Nuget Standard
      run: nuget restore src/Rg.Plugins.Popup.sln 
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with dotnet
      run: msbuild src/Rg.Plugins.Popup.sln -property:Configuration=Release
    - name: Nuget Pack
      run:  nuget pack  nuspec/Rg.Plugins.Popup.nuspec
    - name: Push Package to nuget
      run: dotnet nuget push **/*.nupkg
             --api-key ${{ secrets.nugetapikey }}
             --source https://api.nuget.org/v3/index.json
